/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javanexuspots.admin.itemDb;

import java.util.List;
import javanexuspots.admin.AdminMainPage;
import javanexuspots.services.ItemService;
import javanexuspots.loginPage.LoginSession;
import javanexuspots.models.InventoryUpdates;
import javanexuspots.models.Item;
import javanexuspots.services.InventoryUpdateService;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus ROG
 */
public class AdminDeleteItem extends javax.swing.JFrame {
    
    private ItemService itemService;
    /**
     * Creates new form AdminAddUser
     */
    public AdminDeleteItem() {
        initComponents();
        this.itemService = new ItemService();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DeleteItemBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        itemIdCmbBox = new javax.swing.JComboBox<>();
        itemNameField = new javax.swing.JLabel();
        reorderLevelField = new javax.swing.JLabel();
        priceField = new javax.swing.JLabel();
        supplierIdField = new javax.swing.JLabel();
        itemCodeCmbBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stockLevelField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ItemID:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Item Name:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Supplier ID:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Item Price (RM):");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reorder Level:");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Existing Item");

        DeleteItemBtn.setBackground(new java.awt.Color(255, 0, 0));
        DeleteItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteItemBtn.setText("Delete Item");
        DeleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        CancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        itemIdCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdCmbBoxActionPerformed(evt);
            }
        });

        itemNameField.setBackground(new java.awt.Color(60, 60, 60));
        itemNameField.setForeground(new java.awt.Color(0, 0, 0));
        itemNameField.setText("Choose Item");
        itemNameField.setToolTipText("");

        reorderLevelField.setBackground(new java.awt.Color(60, 60, 60));
        reorderLevelField.setForeground(new java.awt.Color(0, 0, 0));
        reorderLevelField.setText("Choose Item");

        priceField.setBackground(new java.awt.Color(60, 60, 60));
        priceField.setForeground(new java.awt.Color(0, 0, 0));
        priceField.setText("Choose Item");
        priceField.setToolTipText("");

        supplierIdField.setBackground(new java.awt.Color(60, 60, 60));
        supplierIdField.setForeground(new java.awt.Color(0, 0, 0));
        supplierIdField.setText("Choose Item");
        supplierIdField.setToolTipText("");

        itemCodeCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeCmbBoxActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Item Code:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Stock Level:");

        stockLevelField.setBackground(new java.awt.Color(60, 60, 60));
        stockLevelField.setForeground(new java.awt.Color(0, 0, 0));
        stockLevelField.setText("Choose Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemIdCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reorderLevelField)
                                    .addComponent(priceField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(stockLevelField)))
                        .addGap(155, 155, 155))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(supplierIdField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(itemNameField)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemIdCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(priceField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reorderLevelField)
                    .addComponent(itemCodeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(stockLevelField))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(itemNameField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(supplierIdField))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteItemBtn)
                    .addComponent(CancelBtn))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemBtnActionPerformed
       
        String selectedItemId = (String) itemIdCmbBox.getSelectedItem();

        // ensure an item is selected
        if (selectedItemId == null || selectedItemId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this item?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                itemService.deleteItem(selectedItemId); //delete item

                JOptionPane.showMessageDialog(this, "Item deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                // log item deletion
                InventoryUpdateService inventoryUpdateService = new InventoryUpdateService();
                InventoryUpdates deleteUpdate = inventoryUpdateService.createDeleteUpdate(selectedItemId);
                inventoryUpdateService.writeInventoryUpdate(deleteUpdate);

                // clear fields and reload combo boxes
                clearFields();
                loadComboBox();
                
                new AdminMainPage().setVisible(true);;
                this.dispose();
                
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteItemBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        new AdminMainPage().setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void itemIdCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdCmbBoxActionPerformed
        String selectedItemId = (String) itemIdCmbBox.getSelectedItem();

        if (selectedItemId != null) {
            Item item = itemService.getItemById(selectedItemId);
            if (item != null) {
                fillItemDetails(item);
                // Update the itemCodeCmbBox to match this item
                itemCodeCmbBox.setSelectedItem(item.getItemCode());
            } else {
                clearFields();
            }
        }        
    }//GEN-LAST:event_itemIdCmbBoxActionPerformed

    private void itemCodeCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeCmbBoxActionPerformed
        String selectedItemCode = (String) itemCodeCmbBox.getSelectedItem();

        if (selectedItemCode != null) {
            Item item = itemService.getItemByCode(selectedItemCode);
            if (item != null) {
                fillItemDetails(item);
                // Update the itemIdCmbBox to match this item
                itemIdCmbBox.setSelectedItem(item.getItemId());
            } else {
                clearFields();
            }
        }
    }//GEN-LAST:event_itemCodeCmbBoxActionPerformed

    
    private void loadComboBox() {
        List<Item> items = itemService.getAllItems();
        DefaultComboBoxModel<String> idModel = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> codeModel = new DefaultComboBoxModel<>();

        for (Item item : items) {
            idModel.addElement(item.getItemId());
            codeModel.addElement(item.getItemCode());
        }

        itemIdCmbBox.setModel(idModel);
        itemCodeCmbBox.setModel(codeModel);

        // Set no selection initially
        itemIdCmbBox.setSelectedIndex(-1);
        itemCodeCmbBox.setSelectedIndex(-1);
        clearFields();
    }

    private void fillItemDetails(Item item) {
        itemNameField.setText(item.getItemName());
        supplierIdField.setText(item.getSupplierId());
        priceField.setText(String.format("RM %.2f", item.getPrice()));
        reorderLevelField.setText(String.valueOf(item.getReorderLevel()));
        stockLevelField.setText(String.valueOf(item.getStockLevel()));
    }

    private void clearFields() {
        itemNameField.setText("Choose Item");
        supplierIdField.setText("Choose Item");
        priceField.setText("Choose Item");
        reorderLevelField.setText("Choose Item");
        stockLevelField.setText("Choose Item");
        itemIdCmbBox.setSelectedIndex(-1);
        itemCodeCmbBox.setSelectedIndex(-1);
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDeleteItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton DeleteItemBtn;
    private javax.swing.JComboBox<String> itemCodeCmbBox;
    private javax.swing.JComboBox<String> itemIdCmbBox;
    private javax.swing.JLabel itemNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceField;
    private javax.swing.JLabel reorderLevelField;
    private javax.swing.JLabel stockLevelField;
    private javax.swing.JLabel supplierIdField;
    // End of variables declaration//GEN-END:variables
}
