/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javanexuspots.admin.itemDb;

import java.util.List;
import javanexuspots.admin.AdminMainPage;
import javanexuspots.loginPage.LoginSession;
import javanexuspots.models.InventoryUpdates;
import javanexuspots.models.Item;
import javanexuspots.models.Supplier;
import javanexuspots.services.InventoryUpdateService;
import javanexuspots.services.ItemService;
import javanexuspots.services.SupplierService;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus ROG
 */
public class AdminEditItem extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddUser
     */
    public AdminEditItem() {
        initComponents();
        loadItemCmbBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EditItemBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        itemNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        supplierIDCmbBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        itemCodeTxtField = new javax.swing.JTextField();
        priceTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reorderLevelTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        StockLevelTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplierIDCmbBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Existing Item");

        EditItemBtn.setBackground(new java.awt.Color(51, 102, 255));
        EditItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditItemBtn.setText("Edit Item");
        EditItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditItemBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        CancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        itemNameTxtField.setText("Choose Item ID");
        itemNameTxtField.setToolTipText("");
        itemNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Supplier ID:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Item Code:");

        itemCodeTxtField.setText("Choose Item ID");
        itemCodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTxtFieldActionPerformed(evt);
            }
        });

        priceTxtField.setText("Choose Item ID");
        priceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Item Price (RM):");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Reorder Level:");

        reorderLevelTxtField.setText("Choose Item ID");
        reorderLevelTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorderLevelTxtFieldActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Stock Level:");

        StockLevelTxtField.setText("Choose Item ID");
        StockLevelTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockLevelTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Item Name:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Item ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemCodeTxtField)
                            .addComponent(supplierIDCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(supplierIDCmbBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StockLevelTxtField)
                            .addComponent(reorderLevelTxtField)
                            .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reorderLevelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StockLevelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(supplierIDCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(itemNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(supplierIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditItemBtn)
                    .addComponent(CancelBtn))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditItemBtnActionPerformed
        String itemId = (String) supplierIDCmbBox1.getSelectedItem();
        String itemCode = itemCodeTxtField.getText().trim();
        String itemName = itemNameTxtField.getText().trim();
        String selectedSupplier = (String) supplierIDCmbBox.getSelectedItem();
        String supplierId = "";

        // validation for commas in all text fields
        if (itemCode.contains(",") || itemName.contains(",") || 
            priceTxtField.getText().contains(",") || 
            reorderLevelTxtField.getText().contains(",") || 
            StockLevelTxtField.getText().contains(",")) {
            JOptionPane.showMessageDialog(this, "Fields cannot contain commas (,).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        // extract supplier ID from the selection from "SupplierName (SupplierId)" format
        if (selectedSupplier != null && selectedSupplier.contains("(") && selectedSupplier.contains(")")) {
            supplierId = selectedSupplier.substring(selectedSupplier.lastIndexOf("(") + 1, selectedSupplier.lastIndexOf(")"));
        }

        ItemService itemService = new ItemService();
        InventoryUpdateService inventoryUpdateService = new InventoryUpdateService();
        List<Item> items = itemService.getAllItems();

        try {
            // get original item data before update
            Item originalItem = items.stream()
                .filter(i -> i.getItemId().equals(itemId))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Item not found"));

            // Parse numeric values
            double price = Double.parseDouble(priceTxtField.getText().trim());
            int reorderLevel = Integer.parseInt(reorderLevelTxtField.getText().trim());
            int stockLevel = Integer.parseInt(StockLevelTxtField.getText().trim());

            // create updated item object
            Item updatedItem = new Item(
                itemId,
                itemCode,
                itemName,
                supplierId,
                price,
                reorderLevel,
                stockLevel
            );

            // update item in database
            String managerId = LoginSession.getCurrentUserSession();
            itemService.updateItem(updatedItem);

            // log the edit details
            int changeInStock = stockLevel - originalItem.getStockLevel(); // calculate stock change
            InventoryUpdates editUpdate = inventoryUpdateService.createEditUpdate(itemId, changeInStock);
            inventoryUpdateService.writeInventoryUpdate(editUpdate);

            JOptionPane.showMessageDialog(this, "Item updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            // clear fields
            itemCodeTxtField.setText("");
            itemNameTxtField.setText("");
            priceTxtField.setText("");
            reorderLevelTxtField.setText("");
            StockLevelTxtField.setText("");
            supplierIDCmbBox.setSelectedIndex(-1);
            supplierIDCmbBox1.setSelectedIndex(-1);

            // return to admin page
            new AdminMainPage().setVisible(true);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for price, reorder level, and stock level", 
                "Validation Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_EditItemBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        new AdminMainPage().setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void itemNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtFieldActionPerformed

    private void priceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtFieldActionPerformed

    private void reorderLevelTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorderLevelTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reorderLevelTxtFieldActionPerformed

    private void StockLevelTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockLevelTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockLevelTxtFieldActionPerformed

    private void itemCodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTxtFieldActionPerformed

    private void loadItemCmbBox() {
        ItemService itemService = new ItemService();
        SupplierService supplierService = new SupplierService();

        List<Item> items = itemService.getAllItems();
        List<Supplier> suppliers = supplierService.getAllSuppliers();
        DefaultComboBoxModel<String> itemIdModel = new DefaultComboBoxModel<>();

        // populate item ID combo box
        for (Item item : items) {
            itemIdModel.addElement(item.getItemId());
        }
        supplierIDCmbBox1.setModel(itemIdModel);

        // setup supplier combo box
        supplierIDCmbBox.removeAllItems();
        for (Supplier supplier : suppliers) {
            String displayText = String.format("%s (%s)", supplier.getSupplierName(), supplier.getSupplierId());
            supplierIDCmbBox.addItem(displayText);
        }

        // fill in fields when item ID is selected
        supplierIDCmbBox1.addActionListener(evt -> {
            String selectedItemId = (String) supplierIDCmbBox1.getSelectedItem();

            for (Item item : items) {
                if (item.getItemId().equals(selectedItemId)) {
                    // populate all fields
                    itemCodeTxtField.setText(item.getItemCode());
                    itemNameTxtField.setText(item.getItemName());
                    priceTxtField.setText(String.valueOf(item.getPrice()));
                    reorderLevelTxtField.setText(String.valueOf(item.getReorderLevel()));
                    StockLevelTxtField.setText(String.valueOf(item.getStockLevel()));

                    // select the correct supplier in combo box
                    String itemSupplierId = item.getSupplierId();
                    for (int i = 0; i < supplierIDCmbBox.getItemCount(); i++) {
                        String supplierEntry = supplierIDCmbBox.getItemAt(i);
                        if (supplierEntry.endsWith("(" + itemSupplierId + ")")) {
                            supplierIDCmbBox.setSelectedIndex(i);
                            break;
                        }
                    }
                    break;
                }
            }
        });

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton EditItemBtn;
    private javax.swing.JTextField StockLevelTxtField;
    private javax.swing.JTextField itemCodeTxtField;
    private javax.swing.JTextField itemNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JTextField reorderLevelTxtField;
    private javax.swing.JComboBox<String> supplierIDCmbBox;
    private javax.swing.JComboBox<String> supplierIDCmbBox1;
    // End of variables declaration//GEN-END:variables
}
