package javanexuspots.inventoryManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javanexuspots.services.ItemService;
import javanexuspots.models.Supplier;
import javanexuspots.services.SupplierService;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus ROG
 */
public class EditSupply extends javax.swing.JFrame {
    
    private final ItemService itemService;
    private final SupplierService supplierService;

    /**
     * Creates new form AdminAddUser
     */
    public EditSupply() {
        initComponents();
        itemService = new ItemService();
        supplierService = new SupplierService();

        loadSupplierIDComboBox();
    }   

    private void loadSupplierIDComboBox() {
            List<Supplier> suppliers = supplierService.getAllSuppliers(); // Fetch suppliers
            DefaultComboBoxModel<String> supplierIdModel = new DefaultComboBoxModel<>();

            for (Supplier supplier : suppliers) {
                supplierIdModel.addElement(supplier.getSupplierId()); // Populate supplier IDs
            }

            supplierIDCmbBox.setModel(supplierIdModel); // Set to ComboBox

            // Load details for the first supplier if the list isn't empty
            if (!suppliers.isEmpty()) {
                String firstSupplierId = suppliers.get(0).getSupplierId();
                supplierIDCmbBox.setSelectedItem(firstSupplierId);
                loadSupplierDetails(firstSupplierId); // Load details
            }

            // Add listener to handle ComboBox changes
            supplierIDCmbBox.addActionListener(evt -> {
                String selectedSupplierId = (String) supplierIDCmbBox.getSelectedItem();
                if (selectedSupplierId != null) {
                    loadSupplierDetails(selectedSupplierId);
                }
            });
        }



        
        
private void loadSupplierDetails(String supplierId) {
    // Retrieve the supplier as Optional
    Optional<Supplier> supplierOptional = supplierService.getSupplierById(supplierId);

    if (supplierOptional.isPresent()) {
        // Extract the Supplier object
        Supplier supplier = supplierOptional.get();

        // Set fields, ensuring null checks
        supplierCodeTxtField.setText(supplier.getSupplierCode() != null ? supplier.getSupplierCode() : "");
        supplierNameTxtField.setText(supplier.getSupplierName() != null ? supplier.getSupplierName() : "");
        contactInfoTxtField.setText(supplier.getContactInfo() != null ? supplier.getContactInfo() : "");
        addressTxtField.setText(supplier.getAddress() != null ? supplier.getAddress() : "");
        itemIDTxtField.setText(supplier.getItemId() != null ? supplier.getItemId() : "");
    } else {
        // Clear fields if supplier is not found
        supplierCodeTxtField.setText("");
        supplierNameTxtField.setText("");
        contactInfoTxtField.setText("");
        addressTxtField.setText("");
        itemIDTxtField.setText("");

        JOptionPane.showMessageDialog(this, "Supplier not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}




        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        supplierCodeTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        supplierNameTxtField = new javax.swing.JTextField();
        itemIDTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactInfoTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        editSupplyBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        supplierIDCmbBox = new javax.swing.JComboBox<>();
        addressTxtField = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Supplier ID:");

        jLabel3.setText("Supplier Code:");

        supplierCodeTxtField.setToolTipText("");
        supplierCodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierCodeTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Address:");

        jLabel5.setText("Supplier Name:");

        supplierNameTxtField.setText("-");
        supplierNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtFieldActionPerformed(evt);
            }
        });

        itemIDTxtField.setText("-");
        itemIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Item ID:");

        jLabel6.setText("Contact Info:");

        contactInfoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactInfoTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Existing Supply");

        editSupplyBtn.setBackground(new java.awt.Color(51, 102, 255));
        editSupplyBtn.setForeground(new java.awt.Color(255, 255, 255));
        editSupplyBtn.setText("Edit Supply");
        editSupplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupplyBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        supplierIDCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIDCmbBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(supplierIDCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplierCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplierNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactInfoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editSupplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(584, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(supplierIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactInfoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(supplierCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(itemIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtn)
                    .addComponent(editSupplyBtn))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel2)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplierCodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierCodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierCodeTxtFieldActionPerformed

    private void supplierNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtFieldActionPerformed

    private void itemIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIDTxtFieldActionPerformed

    private void contactInfoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactInfoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactInfoTxtFieldActionPerformed

    private void editSupplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupplyBtnActionPerformed
        String supplierId = (String) supplierIDCmbBox.getSelectedItem();
        String supplierCode = supplierCodeTxtField.getText().trim();
        String supplierName = supplierNameTxtField.getText().trim();
        String contactInfo = contactInfoTxtField.getText().trim();
        String address = addressTxtField.getText().trim();
        String itemId = itemIDTxtField.getText().trim();

        try {
            // Validate supplier ID
            if (supplierId == null || supplierId.isEmpty()) {
                throw new IllegalArgumentException("No Supplier ID selected.");
            }

            // Validate required fields
            if (supplierCode.isEmpty() || supplierName.isEmpty()) {
                throw new IllegalArgumentException("Supplier Code and Supplier Name cannot be empty.");
            }

            // Validate item ID
            if (itemId.isEmpty() || itemService.getItemById(itemId) == null) {
                throw new IllegalArgumentException("Invalid Item ID. Please ensure the item exists.");
            }

            // Validate contact info and address
            if (contactInfo.isEmpty()) {
                throw new IllegalArgumentException("Contact Info cannot be empty.");
            }
            if (address.isEmpty()) {
                throw new IllegalArgumentException("Address cannot be empty.");
            }

            // Update the supplier in the database
            Supplier updatedSupplier = new Supplier(supplierId, supplierCode, supplierName, contactInfo, address, itemId);
            supplierService.updateSupplier(updatedSupplier);

            JOptionPane.showMessageDialog(this, "Supplier updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear fields
            supplierCodeTxtField.setText("");
            supplierNameTxtField.setText("");
            contactInfoTxtField.setText("");
            addressTxtField.setText("");
            itemIDTxtField.setText("");

            // Close the form or navigate back
            this.dispose();
                } catch (IllegalArgumentException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Error", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

    }//GEN-LAST:event_editSupplyBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        new MainMenu().setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void supplierIDCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIDCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIDCmbBoxActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSupply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JTextField contactInfoTxtField;
    private javax.swing.JButton editSupplyBtn;
    private javax.swing.JTextField itemIDTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField supplierCodeTxtField;
    private javax.swing.JComboBox<String> supplierIDCmbBox;
    private javax.swing.JTextField supplierNameTxtField;
    // End of variables declaration//GEN-END:variables
}
